
 #CC = i686-w64-mingw32.static-gcc -Wall
 LIB = -lwsock32 -lpthread -lwinmm

 ifeq "x$(PREFIX)" "x"
  PREFIX = $(PS2DEV)
 endif

 all: bin/fsclient.exe bin/ps2client.exe

 clean:
	rm -f obj/*.o bin/*client*

 #################
 ## CLIENT LIBS ##
 #################

 OFILES += obj/network.o
 obj/network.o: src/network.c src/network.h
	@mkdir -p obj
	$(CC) $(INC) -c src/network.c -o obj/network.o

 OFILES += obj/ps2link.o
 obj/ps2link.o: src/ps2link.c src/ps2link.h
	@mkdir -p obj
	$(CC) $(INC) -c src/ps2link.c -o obj/ps2link.o

 OFILES += obj/ps2netfs.o
 obj/ps2netfs.o: src/ps2netfs.c
	@mkdir -p obj
	$(CC) $(INC) -c src/ps2netfs.c -o obj/ps2netfs.o

 OFILES += obj/utility.o
 obj/utility.o: src/utility.c src/utility.h
	@mkdir -p obj
	$(CC) $(INC) -c src/utility.c -o obj/utility.o

 OFILES += obj/telemetry.o
 obj/telemetry.o: src/telemetry.c src/telemetry.h src/dctool-telemetry.h
	@mkdir -p obj
	$(CC) $(INC) -c src/telemetry.c -o obj/telemetry.o

 OFILES += obj/input.o
 obj/input.o: src/input.c src/input.h src/ps2link-input.h
	@mkdir -p obj
	$(CC) $(INC) -c src/input.c -o obj/input.o

 ###################
 ## INPUT MODULES ##
 ###################

 # --input <name> loads input-<name>.so beside ps2client.exe. The gamepad
 # module embeds static SDL3 from lib/SDL3, which is not committed: a missing
 # copy is fetched at the version lib/sdl3.version pins (lib/update-sdl3.sh).
 INPUT_CC = $(CC) -O2 -std=c99 -Wall -Wextra -shared -static-libgcc -static -Isrc
 SDL3 = lib/SDL3

 input: bin/input-keyboard.so bin/input-gamepad.so bin/input-bridge.so

 bin/input-keyboard.so: input/keyboard.c src/ps2link-input.h
	@mkdir -p bin
	$(INPUT_CC) -o $@ input/keyboard.c

 bin/input-gamepad.so: input/gamepad.c src/ps2link-input.h $(SDL3)/lib/libSDL3.a
	@mkdir -p bin
	$(INPUT_CC) -I$(SDL3)/include -o $@ input/gamepad.c $(SDL3)/lib/libSDL3.a $(shell cat $(SDL3)/libs.txt)

 # The recipe reads libs.txt when it runs, after this fetch.
 $(SDL3)/lib/libSDL3.a:
	sh lib/update-sdl3.sh $(shell cat lib/sdl3.version)

 bin/input-bridge.so: input/bridge.c src/ps2link-input.h
	@mkdir -p bin
	$(INPUT_CC) -o $@ input/bridge.c -lws2_32

 .PHONY: input

 #####################
 ## CLIENT PROGRAMS ##
 #####################

 bin/fsclient.exe: $(OFILES) src/fsclient.c
	@mkdir -p bin
	$(CC) $(INC) $(OFILES) src/fsclient.c -o bin/fsclient.exe $(LIB)

 bin/ps2client.exe: $(OFILES) src/ps2client.c
	@mkdir -p bin
	$(CC) $(INC) $(OFILES) src/ps2client.c -o bin/ps2client.exe $(LIB)
